import { Question } from "@/types";

export const general: Question[] = [
    { question: 'What is ISSIMI?', answer: 'ISSIMI is a full-service marketplace to buy and sell the most extraordinary motor vehicles in the world. We pride ourselves on delivering an exceptional client experience, building trust with our community, and promoting transparency with every transaction. With a team boasting over 100 years of combined experience in the specialty car market, we are uniquely equipped to help collectors navigate the sometimes opaque world of car collecting.' },
    {question: 'What does "ISSIMI" mean?', answer: "The name ISSIMI, derived from the Italian language's superlative structure, reflects our high standards. This linguistic tribute to the exceptional is a reflection of our steadfast commitment to quality. By embodying the spirit of the 'best of the best', ISSIMI underlines our promise to offer a curated selection of the most remarkable collector cars from around the globe."}
]

export const selling: Question[] = [ 
    { question: 'What vehicles does ISSIMI accept?', answer: "We specialize in modern supercars and classic sports cars but we are open to anything interesting - show us what you have." },
    { question: 'What information do you need to sell my vehicle?', answer: "The more information the better - at a minimum, year, make, model, miles, VIN and recent service records. But if there is more to know about your car’s history, we would love to hear it." },
    { question: "What do you do to prepare my vehicle for sale?", answer: "When the vehicle arrives, we wash it, give it a thorough inspection and point out any recommended repairs - most of which we can carry out in house. Some repairs we recommend performing prior to a sale, some we will recommend to leave. We want to make sure your vehicle is presented in the best possible light. Then, it gets photographed and a detailed description is written prior to going live." },
    { question: "How does the auction process work once my vehicle is listed?", answer: "Once live on ISSIMI.com, your listing will be presented before serious, qualified enthusiasts and collectors across the globe. These buyers may then offer your full asking price or below, and if you choose to accept an offer, it will then become the starting price for a 72-hour, no-reserve auction. This ensures you get the highest possible outcome with your listing. \n \n If additional bids yield a higher final hammer price than the auction starting price, ISSIMI will collect a performance fee of 15% of the difference between those two values." },
    { question: "Can I withdraw my vehicle after it has been listed?", answer: "No. If a car is withdrawn during the auction, you are subject to a $400 cancellation charge per our consignment agreement." },
    { question: "What happens if my listing does not get any offers?", answer: "With so many variables at play, it can be hard to set an asking price. We are constantly monitoring the listings as well as watching the current market to gather the most up to date pricing information. We suggest adjusting your asking price to garner more interest and can help you determine where you should adjust to." },
    { question: "What happens after someone wins the auction for my vehicle?", answer: "Leave the heavy lifting to us. When your car sells, we will reach out to the buyer and get all the necessary details and receive their payment. All you need to do is give us the signed title and your payment will be issued." },
    { question: "What fees do you charge?", answer: "We charge a seller’s premium of 5% of the final hammer price of the auction. This fee covers transportation to an ISSIMI facility, all of the vehicle preparation as well as all advertising and sales initiatives. When a sale is handled by ISSIMI, your car receives the same (if not better) treatment than most conventional dealers or auction houses, who routinely command premiums of 10-15% or more from a seller." },
    { question: "How long is my car under contract with ISSIMI when I agree to list it?", answer: "Your consignment agreement will specify how long your vehicle is exclusively for sale with us." }, 
    {question: 'What happens if the car doesn’t sell at the end of my listing period?', answer: "You will have the option to receive your vehicle back or continue to advertise the vehicle on our platform."}
]