
import '/public/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import PorscheNavbar, { Footer } from './homePage'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className='relative'>
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
            <PorscheNavbar/>
            <body className='bg-gray-200 h-auto relative -z-10'>
      
                {children}
                <Footer/>
            </body>
               
        </html>
    )
}
