import { SupercarData } from "@/types";

export const SuperCarData: SupercarData[] = [
  {
    firstImage: "gtronic2.jpg",
    secondImage: "gtronic.jpg",
    shortName: "GTRONIC",
    src: "gtronic",
    name: "9FF GTronic",
    tag: "GTronic - Acceleration is its passion",
    vehicle: "Base vehicle 997 Turbo 3.6 (coupé or convertible possible)",
    vehicleUpgrades: [
      "Aluminium bonnet and doors",
      '9FF body modification "GTurbo"',
      "Front spoiler, side skirts, rear skirt, rear spoiler",
      "Wider carbon front wing (+ 2.5cm) with wheel house vents",
      "LED tail lamps, LED daytime running lamps and indicators",
      "9FF airbag steering wheel with paddle shifters on request",
      "Roll cage on request",
      "Recaro lightweight bucket seats on request",
      "1,550 kg unladen weight",
    ],
    engineUpgrades: [
      "3.9 litre displacement engine",
      "9FF engine block reinforcement",
      "Dual piston oil-spray cooling per cylinder",
      "9FF / Pankl forged pistons",
      "9FF steel cylinders",
      "9FF Pankl titanium connecting rods",
      "9FF RSR crankshaft 82.4 mm",
      "9FF cylinder heads with large valves and ducts",
      '9FF camshafts "VarioCam Plus" with variable intake position',
      "9FF aluminium billet intake manifold fully welded",
      "12 dual injection nozzles",
      "9FF fuel system with 3 fuel pumps and pressure regulator controlled by boost pressure",
      "9FF stainless steel header",
      "Billet PTX1200R turbocharger with ball bearings",
      "External wastegates with dual port control",
      "3 stage boost control automatic / speed-dependent",
      "9FF stainless steel exhaust system with valve control and metal cats",
      "9FF carbon airbox with large HFMs and performance air filter",
      "Dual 45 mm recirculating blowoff valve",
      "9FF high pressure MAP sensor",
      "1,200+ hp / 882 KW at 7,200 rpm",
      "1,150 Nm at 4,700 rpm",
      "7,300 rpm switching speed",
      "1.8 bar boost pressure (0.9 bar = 670 hp and 1.5 bar switched)",
      "104 mm x 82.4 mm (bore x stroke)",
    ],
    transmissionUpgrades: [
      "Base transmission: 997 Turbo 5-speed Tiptronic",
      "All-wheel drive 997 Turbo, electronically controlled",
      '9FF reinforcement to "GTronic"',
      "Reinforced fins for all gears with special coating",
      "Reinforced freewheels",
      "Reinforced oil pump for higher system pressure",
      "Extra strong 9FF limited slip differential 40 / 60%",
      "Reinforced rear drive shafts",
      "TCU reprogramming",
      "7,300 rpm switching speed",
      "Shorter switching times",
      "Release for 1,200 Nm max. torque",
      "9FF reinforced torque converter",
      "Start-up speed with active Launch-Control: 3,200 rpm",
      "Additional front oil cooler",
    ],
    wheelUpgrades: [
      "CERAMIC brake system",
      "Front axle 396 x 34mm with 6-piston caliper",
      "Rear axle 365 x 28mm with 4-piston caliper",
      "Porsche PCCB SUPERCUP brake pads Pagid-GREEN",
      "997 Turbo hydraulic unit ABS / PSM / Traction Control",
      '9FF light-alloy wheels model "GTronic-20" (forged, milled)',
      'Front 9 x 20“ with 245/30 ZR 20" Continental SC5',
      'Rear 12 x 20“ with 325 / 25 ZR 20" Continental SC5',
    ],
    description: [
      "We'll build you an automobile on the basis of a GT3 or GT3 RS that combines the sporty driving behaviour of the base vehicle with the performance of a turbo vehicle.",
      "In order to always be perfectly equipped both on the racetrack as well as on the motorway, you have the choice among various transmissions as well as power levels ranging from 750 hp to 1200 hp.",
      "The GTurbo is an ideal candidate for an understatement. What's on the inside -if you so desire - won't be revealed on the outside. Its breath-taking acceleration and top speed lead to a driving experience that you can peacefully enjoy for yourself.",
      "We can also fully meet your wishes for individuality when designing the interior",
      'In the following outlined technical specifications, we would like to introduce you to the model "R" as an example from our GTurbo series. Please get in touch with us in order to show you all possibilities in connection with this particular vehicle. It\'s "Your Car" we\'re building after all.',
    ],
    performanceTimes: [
      "0-100 kph: 2.5 s",
      "0-200 kph: 6.3 s",
      "0-300 kph: 13.5 s",
      "100-200 kph: 3.8 s",
      "200-300 kph: 6.8 s",
      "Vmax: 355 kph",
    ],
    chassisUpgrades: [
      "Height adjustable 9FF / Bilstein coilover suspension with PASM function",
      "Aluminium shock absorbers",
      "60 mm dual racing springs",
      "Rigid front aluminium strut mount",
      "Reinforced control arm rear axle",
      "Longer front control arm for wider track (countering understeering!)",
      "Front axle with adjustable stabilizer",
      "Hydraulic power steering",
      "Level control on front axle 55 mm up-down",
    ],
  },
  {
    firstImage: "gturbo2.jpg",
    secondImage: "gturbo.jpg",
    shortName: "GTurbo",
    src: "gturbo",
    name: "9FF GTurbo",
    tag: "GTurbo - a name for those hungry for performance",
    vehicle: "Base vehicle 997 GT3 MK1 (3.6 and 3.8 possible)",
    vehicleUpgrades: [
      " Aluminum front hood and doors",
      " Extreme vehicle weight reduction",

      " Kevlar / carbon roof skin",

      " Interior panels only in the front interior area",

      " Recaro lightweight bucket seats in Alcantara",
      " 9FF air inlets/outlets for intercooling",

      "RS rear wing",

      "CUP front lip",
      "1,210 kg curb weight",
    ],
    engineUpgrades: [
      " 3.9 liter displacement engine",
      "9FF engine block reinforcement",
      "Double piston spray oil cooling per cylinder",
      "9FF / Pankl forged pistons",
      "9FF steel cylinder",
      "9FF Pankl titanium connecting rod",
      "9FF RS crankshaft",
      "9FF cylinder heads with large valves and channels",
      "9FF camshafts 'VarioCam' with variable inlet position",
      "9FF aluminum intake manifold fully welded",
      "Dual injectors",
      "9FF petrol system and pressure regulator boost pressure controlled",
      "9FF stainless steel manifold",
      "Garrett GT1200R turbocharger with ball bearings and water-cooled",
      "External waste gates",
      "3-stage boost pressure control with control buttons on the steering wheel",
      "9FF exhaust system with titanium rear silencer and flap control",
      "9FF carbon air filter box with large fresh air intake and sports air filter",
      "Double diverter air valve",
      "Changed MAP sensor",
      "1,200+ HP / 882 KW at 8,100 rpm",
      "1,150 Nm at 5,800 rpm",
      "8,200 rpm speed limiter",
      "1.6 bar boost pressure (0.8 and 1.2 bar switchable)",
      "104mm x 76.4mm (bore x stroke)",
    ],
    chassisUpgrades: [
      "Height-adjustable 9FF / Bilstein chassis",
      "Aluminum shock absorbers",
      "60mm racing springs",
      "Rigid aluminum dome bearings",
      "Reinforced wishbones VA + RA",
      "VA and HA with adjustable stabilizer",
      "Electro-hydraulic power steering",
    ],
    transmissionUpgrades: [
      "Sequential HOLINGER 6-speed racing transmission",
      "Reinforced and straight-toothed",
      "Gear ratios: 3.17 1.89 1.41 1.15 0.93 0.73 (axis 3.44:1)",
      "Extra strong 9FF limited slip differential 40 / 60%",
      "Reinforced drive shafts with larger internal joints",
      "3-disc sinter clutch",
      "Hydraulic central release bearing",
      "Shifting up without using the clutch",
      "Automatic full throttle “9FF Power Shift” (Engine Cut) system",
    ],
    wheelUpgrades: [
      "997 GT2 PCCB brake system",
      "VA 380x34mm with 6-piston brake caliper",
      "RA 350x28mm with 4-piston brake caliper",
      "Porsche SUPERCUP brake pads",
      "997 GT2 hydraulic unit",

      " 9FF light alloy wheels type “GTurbo”",
      'VA 8.5 x 19" with 245 / 35 ZR 19" DUNLOP SportMaxx GT',
      'RA 11 x 19" with 315 / 30 ZR 19" DUNLOP SportMaxx GT',
    ],
    performanceTimes: [
      "0-100km/h: 3.2s",

      "0-200km/h: 6.7s",

      "0-300 km/h: 12.4s",

      "100-200km/h: 3.5s",

      "200-300 km/h: 5.7s",
      "Vmax: 395 km/h",
    ],
    description: [
      "Based on a GT3 or GT3 RS, we build a car for you that combines the sporty driving behavior of the base vehicle with the performance of a turbo vehicle.",
      "In order to always be perfectly prepared both on the racetrack and on the highway, you have the choice between different transmissions and performance levels ranging from 750 hp to 1200 hp.",
      "The GTurbo is ideal for understatement. What's inside will not be visible from the outside - if you wish. Its breathtaking acceleration and top speed result in a driving experience that you can enjoy in silence.",

      "We can also fully meet your wishes for individuality when designing the interior.",
      "In the technical specifications described below, we will introduce you to the “R” model from our GTurbo series as an example. Please contact us to show you all the options related to this special vehicle. After all, we build “your car”.",
    ],
  },
  {
    src: "gt9",
    firstImage: "gt92.jpg",
    secondImage: "gt93.jpg",
    shortName: "GT9",
    name: "9FF GT9",
    tag: "GT9 - our masterpiece in terms of performance.",
    vehicleUpgrades: [
      "+ 2-seater super sports car",
      "Mid-engine design",
      "Load-bearing 9ff tubular frame constructionIntegrated roll cage with door crosses for high safety",
      "Front end in box design for “crash safety”",
      "1-piece lightweight carbon fiber body",
      "Wheel arch extensions at the front and rear",
      "Carbon fiber front hood",
      "Carbon fiber doors with side impact protection",
      "Front window made of laminated safety glass",
      "Side and rear windows made of Makrolon Plexiglas",
      "9FF / Recaro lightweight bucket seats",
      "9FF air inlets/outlets in carbon fiber",
      "Visible carbon fiber rear wing",
      "4-part smooth underbody with integrated front lip and rear diffuser",
      "",
      "+ Curb weight: 1,240 kg",
      "Height: 1,100 mm",
      "Length: 4,720 mm",
      "Width: 2,045 mm",
      "Wheelbase: 2,700 mm",
      "Cd value: 0.325",
    ],
    engineUpgrades: [
      "+ 6-cylinder boxer engine with bi-turbo charging",
      "3.6 liter displacement",
      "9FF engine block reinforcement",
      "Double piston spray oil cooling per cylinder",
      "Forged pistons",
      "Aluminum cylinder Nikasil coated",
      "9FF / Pankl titanium connecting rods",
      "9FF RS crankshaft",
      "9FF cylinder heads with large valves and channels",
      "9FF camshafts “VarioCamPlus” with variable inlet position",
      "Flow-efficient plastic intake bridge",
      "9FF petrol system and pressure regulator boost pressure controlled",
      "9FF stainless steel manifold",
      "VGT-750R turbocharger with plain bearings and water-cooled",
      "Electronically angle-controlled turbine blades for boost pressure control",
      "2-stage boost pressure control with control switch on the steering wheel",
      "Aluminum intercooler with separate body inlet and outlet",
      "Fan for additional intercooling",
      "9FF exhaust system with rear silencers and flap control",
      "HJS 200cell Motorsport metal catalytic converters OBDII / EURO 5",
      "9FF air filter boxes with large fresh air intake and sports air filters",
      "Integrated diverter air valves",
      "Changed MAP sensor",
      "+ 750 HP / 551 KW at 6,800 rpm",
      "910 Nm from 2,950 to 5,800 rpm",
      "7,400 rpm speed limiter",
      "1.6 bar boost pressure (can be reduced to 1.0 bar via switch)",
      "100mm x 76.4mm (bore x stroke)",
    ],
    chassisUpgrades: [
      " Height-adjustable 9FF / JRZ chassis",
      "Aluminum shock absorber with reservoir",
      "Damper 3-way adjustable",
      "60mm double racing springs",
      "Rigid aluminum dome bearings",
      "Reinforced wishbones VA + HA",
      "Front axle “McPherson” system",
      "Rear axle with push-rod actuation",
      "All axle struts with metal joint bearings",
      "VA and HA with 4-way adjustable stabilizer",
      "Electro-hydraulic power steering",
    ],
    transmissionUpgrades: [
      "H-shifted 6-speed transmission at the rear",
      "Reinforced and helical teeth for quiet running",
      "Gear ratios: 3.17 1.89 1.41 1.09 0.89 0.75 (axis 3.44:1)",
      "Extra strong 9ff limited slip differential 40/60%",
      "Reinforced drive shafts with large internal joints",
      "Extra light aluminum flywheel",
      "9FF 1-disc clutch with organic friction lining",
      "Hydraulic release bearing",
      "Automatic full throttle “9ff power shift” (engine cut) system",
    ],
    wheelUpgrades: [
      "2-piece brake discs with aluminum pot",
      "VA 380x34mm with 6-piston brake caliper",
      "RA 350x28mm with 4-piston brake caliper",
      "9FF / Pagid Sport brake pads",
      "PSM / ABS 4-channel hydraulic unit and control",
      "PSM can be switched off",
      "9FF light alloy wheels type “9ff-BBS-CS”",
      'VA 10.5 x 18" with 285 / 35 ZR 18" Michelin CUP tires',
      'RA 13.5 x 19" with 345 / 30 ZR 19" Michelin CUP tires',
    ],
    description: [
      "Winner of multiple international awards, we present to you the current world record vehicle from 9FF.",
      "With the top model Vmax we have demonstrably achieved almost Mach 0.5 under the eyes of the international motorsport press. Specifically: 437 km/h.",
      "Our Amax model variant impressed the experts with its unique acceleration. It catapults the ambitious driver from zero to 300 km/h in significantly less than 13 seconds.",
      "The ultimate, sporty driving experience is at the forefront of this special vehicle and goes beyond all previously known dimensions.",
      "It is not for nothing that, after several years of development work, we are a little proud to be able to offer you - despite the strict registration regulations within the EU - a unique sports car with an output of up to 1,400 hp, which you can use without restriction, especially on public roads can.",
      "The GT9 is anything but a production vehicle. It is individually built for you as a lover of special vehicles. Of course, you personally determine the desired performance level and transmission configuration, which can be expanded at any time.",
      "You also have a free choice when it comes to the interior. If the consistent lightweight construction seems too puristic for you, we will design an interior for you that couldn't be more individual.",
      "The following vehicle specifications are only exemplary and refer to the “Club Sport” edition. With its 750 hp, the GT9 CS - unfortunately you can't get less - is our tamest model.",
    ],
    performanceTimes: [
      "0-100km/h: 3.6s",
      "0-200km/h: 8.8s",
      "0-300km/h: 19.5s",
      "100-200 km/h: 5.2s",
      "200-300 km/h: 10.4s",
      "Vmax: 364 km/h",
    ],
  },
  {
    firstImage: "speed91.jpg",
    secondImage: "speed92.jpg",
    shortName: "Speed9",
    src: "speed9",
    tag: "Speed9 - Allow us to give you some fresh thoughts.",
    name: "9FF Speed9",
    vehicleUpgrades: [
      "2-seater super sports car",
      "Mid-engine design",
      "Load-bearing 9ff tubular frame constructionIntegrated roll cage with door crosses for high safety",
      "Front end in box design for “crash safety”",
      "1-piece lightweight carbon fiber body",
      "Wheel arch extensions at the front and rear",
      "Carbon fiber front hood",
      "Carbon fiber doors with side impact protection",
      "Front window made of laminated safety glass",
      "Side and rear windows made of Makrolon Plexiglas",
      "9FF / Recaro lightweight bucket seats",
      "9FF air inlets/outlets in carbon fiber",
      "Visible carbon fiber rear wing",
      "4-part smooth underbody with integrated front lip and rear diffuser",
      "Curb weight: 1,240 kg",
      "Height: 1,100 mm",
      "Length: 4,720 mm",
      "Width: 2,045 mm",
      "Wheelbase: 2,700 mm",
      "Cd value: 0.325",
    ],
    engineUpgrades: [
      "9FF sports exhaust system “Speed9 Edition”",
      "9FF 100 cell sports catalytic converters",
      "9FF F700 VTG turbocharger",
      "9FF intercooler",
      "9FF stainless steel manifold",
      "9FF engine control unit programming",
      "9FF sports air filter",
    ],
    transmissionUpgrades: ["6-speed manual transmission or Tiptronic"],
    chassisUpgrades: [
      "9FF “Speed9” wide body (Base: Turbo)",
      "9FF “Speed9 Aerodynamics” consisting of:",
      "9FF front apron",
      "9FF side skirts",
      "9FF rear apron",
      "Complete 9FF leather interior",
      "9FF sports steering wheel",
      "9FF Speed9 lightweight seats",
      "Leather dashboard",
      "Leather door panels",
      "9FF “Speed9” roll bar",
      "9FF Design Instruments",
      " PASM Sport shock absorber",

      " adjustable VA and HA stabilizer",

      " Springs with spacers",

      " 4 aluminum spring plates",
    ],
    wheelUpgrades: [
      '9FF 19" rims with central locking',
      'Front axle 8.5" x 19" - 235/35-ZR 19',
      "Rear axle 11.0 x 19“ - 295/30-ZR 19",
      "Continental Force Contact sports tires",
      "2 VA PCCB brake discs 380mm x 32mm",
      "2 VA 6-piston brake calipers",
      "2 sets of special brake pads",
      "2 HA PCCB brake discs 350mm x 28mm",
    ],
    description: [
      "The 9FF Speed9 is the ultimate open air festival, staged just for you, alone or with pleasant company. And it is also our sunniest.",
      "The combination of fresh air and rich engine sound are the trademark of the 9FF Speed9. If you add the integrated audio system perfected for open-air driving with your favorite music, it becomes the ultimate driving experience that you will remember fondly and for a long time.",
      "The Speed ​​9 is more than a convertible. It is the Harley of road vehicles. It is just as suitable for cruising and strolling as it is for quickly reaching your destination - but with the comfort and safety of 4 wheels.",
      "Its elegant interior, its special shape and its performance make it unique. Experience it on a test drive.",
      "We are of course aware of the biggest concerns about our sunniest vehicle. But we won't leave you out in the cold here either: A tailor-made tarpaulin or hardtop ensures that the 9FF Speed ​​9 is suitable for all weathers in no time at all, up to a speed of 299 km/h.",
    ],
  },
];
