import { SupercarData } from "@/types";

export const SuperCarData: SupercarData[] = [ 
    {
        firstImage: 'gtronic2.jpg',
        secondImage: 'gtronic.jpg',
        shortName: 'GTRONIC',
        src: 'gtronic',
        name: '9FF GTronic',
        tag: 'GTronic - Acceleration is its passion',
        vehicle: 'Base vehicle 997 Turbo 3.6 (coupé or convertible possible)',
        vehicleUpgrades: [
            "Aluminium bonnet and doors",
            '9FF body modification "GTurbo"',
            "Front spoiler, side skirts, rear skirt, rear spoiler",
            "Wider carbon front wing (+ 2.5cm) with wheel house vents",
            "LED tail lamps, LED daytime running lamps and indicators",
            "9FF airbag steering wheel with paddle shifters on request",
            "Roll cage on request",
            "Recaro lightweight bucket seats on request",
            "1,550 kg unladen weight",
        ], 
        engineUpgrades: [ "3.9 litre displacement engine",
        "9FF engine block reinforcement",
        "Dual piston oil-spray cooling per cylinder",
        "9FF / Pankl forged pistons",
        "9FF steel cylinders",
        "9FF Pankl titanium connecting rods",
        "9FF RSR crankshaft 82.4 mm",
        "9FF cylinder heads with large valves and ducts",
        '9FF camshafts "VarioCam Plus" with variable intake position',
        "9FF aluminium billet intake manifold fully welded",
        "12 dual injection nozzles",
        "9FF fuel system with 3 fuel pumps and pressure regulator controlled by boost pressure",
        "9FF stainless steel header",
        "Billet PTX1200R turbocharger with ball bearings",
        "External wastegates with dual port control",
        "3 stage boost control automatic / speed-dependent",
        "9FF stainless steel exhaust system with valve control and metal cats",
        "9FF carbon airbox with large HFMs and performance air filter",
        "Dual 45 mm recirculating blowoff valve",
        "9FF high pressure MAP sensor",
        "1,200+ hp / 882 KW at 7,200 rpm",
        "1,150 Nm at 4,700 rpm",
        "7,300 rpm switching speed",
        "1.8 bar boost pressure (0.9 bar = 670 hp and 1.5 bar switched)",
        "104 mm x 82.4 mm (bore x stroke)",],
        transmissionUpgrades: [  "Base transmission: 997 Turbo 5-speed Tiptronic",
        "All-wheel drive 997 Turbo, electronically controlled",
        '9FF reinforcement to "GTronic"',
        "Reinforced fins for all gears with special coating",
        "Reinforced freewheels",
        "Reinforced oil pump for higher system pressure",
        "Extra strong 9FF limited slip differential 40 / 60%",
        "Reinforced rear drive shafts",
        "TCU reprogramming",
        "7,300 rpm switching speed",
        "Shorter switching times",
        "Release for 1,200 Nm max. torque",
        "9FF reinforced torque converter",
        "Start-up speed with active Launch-Control: 3,200 rpm",
        "Additional front oil cooler",],
        wheelUpgrades: [  "CERAMIC brake system",
        "Front axle 396 x 34mm with 6-piston caliper",
        "Rear axle 365 x 28mm with 4-piston caliper",
        "Porsche PCCB SUPERCUP brake pads Pagid-GREEN",
        "997 Turbo hydraulic unit ABS / PSM / Traction Control", 
        '9FF light-alloy wheels model "GTronic-20" (forged, milled)',
        'Front 9 x 20“ with 245/30 ZR 20" Continental SC5',
        'Rear 12 x 20“ with 325 / 25 ZR 20" Continental SC5',],
        description: [
            "We'll build you an automobile on the basis of a GT3 or GT3 RS that combines the sporty driving behaviour of the base vehicle with the performance of a turbo vehicle.",
             "In order to always be perfectly equipped both on the racetrack as well as on the motorway, you have the choice among various transmissions as well as power levels ranging from 750 hp to 1200 hp.",
             "The GTurbo is an ideal candidate for an understatement. What's on the inside -if you so desire - won't be revealed on the outside. Its breath-taking acceleration and top speed lead to a driving experience that you can peacefully enjoy for yourself.",
             "We can also fully meet your wishes for individuality when designing the interior",
             "In the following outlined technical specifications, we would like to introduce you to the model \"R\" as an example from our GTurbo series. Please get in touch with us in order to show you all possibilities in connection with this particular vehicle. It's \"Your Car\" we're building after all."
        ],
        performanceTimes: [  
        "0-100 kph: 2.5 s",
        "0-200 kph: 6.3 s",
        "0-300 kph: 13.5 s",
        "100-200 kph: 3.8 s",
        "200-300 kph: 6.8 s",
        "Vmax: 355 kph",],
        chassisUpgrades: [
             "Height adjustable 9FF / Bilstein coilover suspension with PASM function",
        "Aluminium shock absorbers",
        "60 mm dual racing springs",
        "Rigid front aluminium strut mount",
        "Reinforced control arm rear axle",
        "Longer front control arm for wider track (countering understeering!)",
        "Front axle with adjustable stabilizer",
        "Hydraulic power steering",
        "Level control on front axle 55 mm up-down",],
    }
]