import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ShopNavbar from './shopNavbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
  
      <body className={'h-auto bg-gray-200'}>{children}</body>
      
    </html>
  )
}
